apps:
- name: cerve-ja-app-back-end
  cwd: ./back-end
  script: npm
  args: "start"
  exec_mode: fork
  max_restarts: 3
  max_memory_restart: 200M
  env:
    PORT: 3001
- name: cerve-ja-app-front-end
  cwd: ./front-end
  script: npm
  args: "run start"
  exec_mode: fork
  max_restarts: 3
  max_memory_restart: 200M
  env:
    PORT: 3000
